#!/usr/bin/env node
/**
 * SPOKE codegen orchestrator — json-schema-to-typescript + typify (Rust).
 */
import { compileFromFile } from "json-schema-to-typescript";
import $RefParser from "@apidevtools/json-schema-ref-parser";
import { glob } from "glob";
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "../../..");
const SCHEMAS_DIR = path.join(REPO_ROOT, "schemas");
const LOCAL_SCHEMAS_DIR = path.join(REPO_ROOT, "tooling/codegen/.schemas-localized");
const DEREF_SCHEMAS_DIR = path.join(REPO_ROOT, "tooling/codegen/.schemas-dereferenced");
const TS_OUT = path.join(REPO_ROOT, "packages/spoke-schemas/src/generated");

const BANNER = `/**
 * AUTO-GENERATED FROM JSON SCHEMA - DO NOT MODIFY
 * Source: schemas/
 * Generated by: pnpm run codegen
 */
`;

const SPOKE_SCHEMA_BASE = "https://spoke42.invalid/schemas/";

function log(msg) {
  console.log(`[spoke-codegen] ${msg}`);
}

function readSchemaTitle(relSchema) {
  const raw = JSON.parse(fs.readFileSync(path.join(SCHEMAS_DIR, relSchema), "utf8"));
  return typeof raw.title === "string" ? raw.title : null;
}

function isDefinitionsOnlySchema(relSchema) {
  const raw = JSON.parse(fs.readFileSync(path.join(SCHEMAS_DIR, relSchema), "utf8"));
  const hasDefinitions = raw.definitions != null || raw.$defs != null;
  const hasObjectBody = raw.type === "object" || raw.properties != null;
  return hasDefinitions && !hasObjectBody;
}

function buildTypeScriptBarrelExport(relSchema, baseName) {
  const title = readSchemaTitle(relSchema);
  if (title && !/\s/.test(title)) {
    return `export type { ${title} } from './${baseName}';`;
  }
  if (isDefinitionsOnlySchema(relSchema)) {
    return `export * from './${baseName}';`;
  }
  return `export * from './${baseName}';`;
}

function localizeSchemaRefs(schemaObj, relSchemaPath) {
  const schemaDir = path.dirname(relSchemaPath);

  if (typeof schemaObj.$id === "string" && schemaObj.$id.startsWith(SPOKE_SCHEMA_BASE)) {
    schemaObj.$id = relSchemaPath;
  }

  const visit = (node) => {
    if (Array.isArray(node)) {
      node.forEach(visit);
      return;
    }
    if (node && typeof node === "object") {
      if (typeof node.$ref === "string" && node.$ref.startsWith(SPOKE_SCHEMA_BASE)) {
        const [filePart, fragment] = node.$ref.slice(SPOKE_SCHEMA_BASE.length).split("#");
        let localized = path.relative(schemaDir, filePart).split(path.sep).join("/");
        if (!localized.startsWith(".")) {
          localized = `./${localized}`;
        }
        node.$ref = fragment ? `${localized}#${fragment}` : localized;
      }
      Object.values(node).forEach(visit);
    }
  };
  visit(schemaObj);
  return schemaObj;
}

async function buildLocalizedSchemaTree() {
  fs.rmSync(LOCAL_SCHEMAS_DIR, { recursive: true, force: true });
  const schemaPaths = await glob("**/*.schema.json", { cwd: SCHEMAS_DIR });
  for (const relSchema of schemaPaths) {
    const raw = JSON.parse(fs.readFileSync(path.join(SCHEMAS_DIR, relSchema), "utf8"));
    const localized = localizeSchemaRefs(structuredClone(raw), relSchema);
    const out = path.join(LOCAL_SCHEMAS_DIR, relSchema);
    fs.mkdirSync(path.dirname(out), { recursive: true });
    fs.writeFileSync(out, JSON.stringify(localized, null, 2));
  }
  return schemaPaths.sort();
}

async function buildDereferencedSchemaTree(schemaPaths) {
  fs.rmSync(DEREF_SCHEMAS_DIR, { recursive: true, force: true });
  for (const relSchema of schemaPaths) {
    const input = path.join(LOCAL_SCHEMAS_DIR, relSchema);
    const bundled = await $RefParser.dereference(input);
    const out = path.join(DEREF_SCHEMAS_DIR, relSchema);
    fs.mkdirSync(path.dirname(out), { recursive: true });
    fs.writeFileSync(out, JSON.stringify(bundled, null, 2));
  }
}

async function generateTypeScript(schemaPaths) {
  log("Generating TypeScript types (json-schema-to-typescript)...");
  fs.rmSync(TS_OUT, { recursive: true, force: true });
  fs.mkdirSync(TS_OUT, { recursive: true });

  for (const relSchema of schemaPaths) {
    const absSchema = path.join(LOCAL_SCHEMAS_DIR, relSchema);
    const relDir = path.dirname(relSchema);
    const baseName = path.basename(relSchema, ".schema.json");
    const outDir = path.join(TS_OUT, relDir);
    const outFile = path.join(outDir, `${baseName}.ts`);
    fs.mkdirSync(outDir, { recursive: true });

    const ts = await compileFromFile(absSchema, {
      bannerComment: BANNER,
      cwd: path.dirname(absSchema),
      unreachableDefinitions: true,
      enableConstEnums: true,
      strictIndexSignatures: true,
      declareExternallyReferenced: true,
    });
    fs.writeFileSync(outFile, ts);
    log(`  wrote ${path.relative(REPO_ROOT, outFile)}`);
  }

  fs.writeFileSync(
    path.join(TS_OUT, "index.ts"),
    `${BANNER}\nexport * from './common';\nexport * from './data';\nexport * from './ops';\n`,
  );

  for (const subdir of ["common", "data", "ops"]) {
    const dirPath = path.join(TS_OUT, subdir);
    if (!fs.existsSync(dirPath)) continue;
    const files = fs
      .readdirSync(dirPath)
      .filter((f) => f.endsWith(".ts") && f !== "index.ts")
      .sort();
    const lines = files.map((f) => {
      const baseName = f.replace(/\.ts$/, "");
      const relSchema = path.posix.join(subdir, `${baseName}.schema.json`);
      return buildTypeScriptBarrelExport(relSchema, baseName);
    });
    fs.writeFileSync(path.join(dirPath, "index.ts"), `${BANNER}\n${lines.join("\n")}\n`);
  }

  log(`TypeScript: ${schemaPaths.length} schema file(s)`);
}

function generateRust() {
  log("Generating Rust types (typify)...");
  const rustGenDir = path.join(REPO_ROOT, "tooling/codegen/rust-gen");
  execSync("cargo run --quiet --release", {
    cwd: rustGenDir,
    stdio: "inherit",
    env: {
      ...process.env,
      SPOKE_REPO_ROOT: REPO_ROOT,
      SPOKE_SCHEMAS_DIR: DEREF_SCHEMAS_DIR,
    },
  });
}

async function main() {
  log(`Repo root: ${REPO_ROOT}`);
  const schemaPaths = await buildLocalizedSchemaTree();
  await buildDereferencedSchemaTree(schemaPaths);
  await generateTypeScript(schemaPaths);
  generateRust();
  log("Codegen complete.");
}

main().catch((err) => {
  console.error("[spoke-codegen] ERROR:", err);
  process.exit(1);
});
