/**
 * Golden vectors for SPOKE connect identity — thin loader over the shared
 * cross-language fixture `tests/fixtures/golden-hello.json` (byte-identical
 * registered copy of the SSOT at
 * `crates/spoke-connect/tests/fixtures/golden-hello.json`; sync gate:
 * `tooling/connect/golden-vector-sync.mjs`).
 *
 * The vector carries BOTH inputs (seed, nonce, manifest) and independently
 * captured outputs (pubkey, peer id, RFC 8785 JCS bytes, libp2p-captured
 * Ed25519 signature). Pinned outputs are transcribed from committed
 * libp2p-captured constants — never regenerated by running the code under
 * test. Tests assert code-under-test output equals these bytes.
 *
 * This module is a test-only helper: it is not in the package `exports` map
 * and not in npm `files` — no production import of the artifact.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import type { HostCapabilityManifest } from "@42ch/spoke-schemas";

interface GoldenManifest {
  host_id: string;
  namespaces: string[];
  capabilities: string[];
  roles: string[];
  schema_version: number;
  extensions: Record<string, never>;
}

interface GoldenResponder {
  nonce: string;
  peer_nonce: string;
  jcs_hex: string;
  signature_b64u: string;
}

interface GoldenHelloFixture {
  version: number;
  seed_hex: string;
  nonce: string;
  manifest: GoldenManifest;
  pubkey_hex: string;
  peer_id: string;
  jcs_hex: string;
  signature_b64u: string;
  manifest_json: string;
  responder: GoldenResponder;
}

const fixtureUrl = new URL("../tests/fixtures/golden-hello.json", import.meta.url);
const fixture = JSON.parse(
  readFileSync(fileURLToPath(fixtureUrl), "utf8"),
) as GoldenHelloFixture;

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

/** Ed25519 seed bytes 1..=32 (from `seed_hex`). */
export const GOLDEN_SEED: Uint8Array = hexToBytes(fixture.seed_hex);

/** Ed25519 public key (from `pubkey_hex`). */
export const GOLDEN_PUBKEY: Uint8Array = hexToBytes(fixture.pubkey_hex);

/** Peer id derived from GOLDEN_PUBKEY (base58btc identity multihash). */
export const GOLDEN_PEER_ID: string = fixture.peer_id;

/** Golden hello nonce (16+ chars, wire floor). */
export const GOLDEN_NONCE: string = fixture.nonce;

/**
 * RFC 8785 JCS UTF-8 bytes (hex) of the signed object
 * `{protocol_version, peer_id, nonce, host}` for the golden manifest —
 * 264 bytes.
 */
export const GOLDEN_JCS_HEX: string = fixture.jcs_hex;

/** base64url (no padding) of the raw 64-byte Ed25519 signature over GOLDEN_JCS_HEX. */
export const GOLDEN_SIGNATURE: string = fixture.signature_b64u;

// ── Responder golden (5-field signed object, dial binding) ─────────────────
// Pinned alongside the initiator vector when the dial-binding mechanism
// landed: the same golden key pair + manifest signed over `peer_nonce` = the
// initiator golden nonce. Both languages sign AND verify this vector
// byte-identically (interop assertion in hello.test.ts / hello_crypto.rs).

/** The responder hello's own nonce (wire floor satisfied). */
export const RESPONDER_NONCE: string = fixture.responder.nonce;

/** The responder's signed `peer_nonce` — the initiator golden nonce. */
export const RESPONDER_PEER_NONCE: string = fixture.responder.peer_nonce;

/**
 * RFC 8785 JCS UTF-8 bytes (hex) of the 5-field signed object
 * `{protocol_version, peer_id, nonce, host, peer_nonce}` — 307 bytes.
 */
export const RESPONDER_JCS_HEX: string = fixture.responder.jcs_hex;

/** base64url (no padding) of the raw 64-byte signature over RESPONDER_JCS_HEX. */
export const RESPONDER_SIGNATURE: string = fixture.responder.signature_b64u;

/**
 * Golden host manifest — `authority` is absent (omit, never `null`), the
 * only non-required manifest member. The canonical bytes in GOLDEN_JCS_HEX
 * contain no `"authority"` member at all.
 */
export function goldenManifest(): HostCapabilityManifest {
  return {
    capabilities: fixture.manifest.capabilities as unknown as [
      string,
      ...string[],
    ],
    extensions: fixture.manifest.extensions,
    host_id: fixture.manifest.host_id,
    // The golden fixture carries an empty namespace list (Rust `Vec::new()`
    // → `"namespaces":[]` in GOLDEN_JCS_HEX). The generated wire type
    // enforces minItems 1 for namespaces and roles, so the fixture diverges
    // at the type level — the JCS bytes are the pinned contract.
    namespaces: fixture.manifest.namespaces as unknown as [string, ...string[]],
    roles: fixture.manifest.roles as unknown as [string, ...string[]],
    schema_version: fixture.manifest.schema_version,
  };
}

/**
 * Schema-conformant host manifest fixture for live wire / interop tests.
 *
 * Unlike `goldenManifest()`, this manifest satisfies the generated
 * `HostCapabilityManifest` type and the JSON Schema as-is: `namespaces`
 * minItems 1 (`^[a-z][a-z0-9_-]*$`), non-empty unique `roles` /
 * `capabilities`, no type casts. The golden manifest above is the pinned
 * **byte contract** (`GOLDEN_JCS_HEX` captures its historical Rust bytes and
 * must never change); this one is the schema-valid fixture for tests that
 * put a hello on the wire or claim wire/schema conformance.
 */
export function schemaConformantManifest(): HostCapabilityManifest {
  return {
    capabilities: ["spoke-baseline"],
    extensions: {},
    host_id: "test-host",
    namespaces: ["toy_world"],
    roles: ["data-store"],
    schema_version: 1,
  };
}
