# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
from dataclasses import dataclass
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import platform


# Used for default argument values
_DEFAULT = object() # type: typing.Any

import ctypes
import struct

class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_spoke_connect_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_spoke_connect_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_spoke_connect_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError(f"junk data left in buffer at end of consume_with_stream {s.remaining()}")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError(f"junk data left in buffer at end of read_with_stream {s.remaining()}")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiFfiConverterByRefBytes:
    """Zero-copy converter for `&[u8]` / `[ByRef] bytes` arguments.

    Only `lower` and `check_lower` are valid — zero-copy byte buffers only
    flow foreign -> Rust, and only in argument position. `lift`, `read`, and
    `write` have no sound implementation here.

    CPython `bytes` objects are immutable and their internal buffer doesn't
    move for the lifetime of the object; the caller must keep the source
    `bytes` alive for the duration of the FFI call.
    """

    @staticmethod
    def check_lower(value):
        # Tighter than `bytes-like`: `lower` uses `ctypes.c_char_p` which only
        # accepts `bytes`/`None`, so fail fast with a matching check.
        if not isinstance(value, bytes):
            raise TypeError("a bytes object is required, not {!r}".format(type(value).__name__))

    @staticmethod
    def lower(value):
        fb = _UniffiForeignBytes()
        if len(value) == 0:
            fb.len = 0
            fb.data = None
        else:
            fb.len = len(value)
            fb.data = ctypes.cast(ctypes.c_char_p(value), ctypes.POINTER(ctypes.c_char))
        return fb

    @staticmethod
    def lift(value):
        raise NotImplementedError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")

    @staticmethod
    def read(buf):
        raise NotImplementedError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    @staticmethod
    def write(value, buf):
        raise NotImplementedError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            packed = struct.pack(format, value)
            if size > 0:
                ctypes.memmove(ctypes.addressof(self.rbuf.data.contents) + self.rbuf.len, packed, size)
    
    def write(self, value):
        length = len(value)
        with self._reserve(length):
            if length > 0:
                ctypes.memmove(ctypes.addressof(self.rbuf.data.contents) + self.rbuf.len, value, length)

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiFfiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiFfiConverterString.lower(repr(e))
# Initial value and increment amount for handles. 
# These ensure that Python-generated handles always have the lowest bit set
_UNIFFI_HANDLEMAP_INITIAL = 1
_UNIFFI_HANDLEMAP_DELTA = 2

class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = _UNIFFI_HANDLEMAP_INITIAL

    def insert(self, obj):
        with self._lock:
            return self._insert(obj)

    """Low-level insert, this assumes `self._lock` is held."""
    def _insert(self, obj):
        handle = self._counter
        self._counter += _UNIFFI_HANDLEMAP_DELTA
        self._map[handle] = obj
        return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.get: Invalid handle {handle}")

    def clone(self, handle):
        try:
            with self._lock:
                obj = self._map[handle]
                return self._insert(obj)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.clone: Invalid handle {handle}")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError(f"_UniffiHandleMap.remove: Invalid handle: {handle}")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("spoke_connect")
    path = os.path.join(os.path.dirname(__file__), libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 30
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_spoke_connect_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    if lib.uniffi_spoke_connect_checksum_func_check_response_correlation() != 57062:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_spoke_connect_checksum_func_derive_peer_id_from_ed25519_pubkey() != 37906:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_spoke_connect_checksum_func_dispatch_allowed() != 25989:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_spoke_connect_checksum_func_is_allowlisted() != 52933:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_spoke_connect_checksum_func_protocol_version() != 50454:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_spoke_connect_checksum_func_required_capability() != 8417:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_spoke_connect_checksum_func_sign_hello_ed25519() != 37896:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_spoke_connect_checksum_func_verify_hello_ed25519() != 15847:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_spoke_connect_checksum_method_inboundsequence_advance() != 17976:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_spoke_connect_checksum_constructor_inboundsequence_new() != 21926:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_spoke_connect_checksum_method_noncestore_check_and_record() != 41909:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_spoke_connect_checksum_constructor_noncestore_new() != 5575:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_spoke_connect_checksum_method_outboundsequence_allocate() != 57422:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_spoke_connect_checksum_constructor_outboundsequence_new() != 6716:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UniffiLib.ffi_spoke_connect_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_spoke_connect_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_spoke_connect_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_spoke_connect_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_spoke_connect_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_spoke_connect_rustbuffer_free.restype = None
_UniffiLib.ffi_spoke_connect_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_spoke_connect_rustbuffer_reserve.restype = _UniffiRustBuffer
_UniffiLib.ffi_spoke_connect_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_spoke_connect_uniffi_contract_version.restype = ctypes.c_uint32
_UniffiLib.uniffi_spoke_connect_checksum_func_check_response_correlation.argtypes = (
)
_UniffiLib.uniffi_spoke_connect_checksum_func_check_response_correlation.restype = ctypes.c_uint16
_UniffiLib.uniffi_spoke_connect_checksum_func_derive_peer_id_from_ed25519_pubkey.argtypes = (
)
_UniffiLib.uniffi_spoke_connect_checksum_func_derive_peer_id_from_ed25519_pubkey.restype = ctypes.c_uint16
_UniffiLib.uniffi_spoke_connect_checksum_func_dispatch_allowed.argtypes = (
)
_UniffiLib.uniffi_spoke_connect_checksum_func_dispatch_allowed.restype = ctypes.c_uint16
_UniffiLib.uniffi_spoke_connect_checksum_func_is_allowlisted.argtypes = (
)
_UniffiLib.uniffi_spoke_connect_checksum_func_is_allowlisted.restype = ctypes.c_uint16
_UniffiLib.uniffi_spoke_connect_checksum_func_protocol_version.argtypes = (
)
_UniffiLib.uniffi_spoke_connect_checksum_func_protocol_version.restype = ctypes.c_uint16
_UniffiLib.uniffi_spoke_connect_checksum_func_required_capability.argtypes = (
)
_UniffiLib.uniffi_spoke_connect_checksum_func_required_capability.restype = ctypes.c_uint16
_UniffiLib.uniffi_spoke_connect_checksum_func_sign_hello_ed25519.argtypes = (
)
_UniffiLib.uniffi_spoke_connect_checksum_func_sign_hello_ed25519.restype = ctypes.c_uint16
_UniffiLib.uniffi_spoke_connect_checksum_func_verify_hello_ed25519.argtypes = (
)
_UniffiLib.uniffi_spoke_connect_checksum_func_verify_hello_ed25519.restype = ctypes.c_uint16
_UniffiLib.uniffi_spoke_connect_checksum_method_inboundsequence_advance.argtypes = (
)
_UniffiLib.uniffi_spoke_connect_checksum_method_inboundsequence_advance.restype = ctypes.c_uint16
_UniffiLib.uniffi_spoke_connect_checksum_constructor_inboundsequence_new.argtypes = (
)
_UniffiLib.uniffi_spoke_connect_checksum_constructor_inboundsequence_new.restype = ctypes.c_uint16
_UniffiLib.uniffi_spoke_connect_checksum_method_noncestore_check_and_record.argtypes = (
)
_UniffiLib.uniffi_spoke_connect_checksum_method_noncestore_check_and_record.restype = ctypes.c_uint16
_UniffiLib.uniffi_spoke_connect_checksum_constructor_noncestore_new.argtypes = (
)
_UniffiLib.uniffi_spoke_connect_checksum_constructor_noncestore_new.restype = ctypes.c_uint16
_UniffiLib.uniffi_spoke_connect_checksum_method_outboundsequence_allocate.argtypes = (
)
_UniffiLib.uniffi_spoke_connect_checksum_method_outboundsequence_allocate.restype = ctypes.c_uint16
_UniffiLib.uniffi_spoke_connect_checksum_constructor_outboundsequence_new.argtypes = (
)
_UniffiLib.uniffi_spoke_connect_checksum_constructor_outboundsequence_new.restype = ctypes.c_uint16
_UniffiLib.uniffi_spoke_connect_fn_func_check_response_correlation.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.c_uint64,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_spoke_connect_fn_func_check_response_correlation.restype = None
_UniffiLib.uniffi_spoke_connect_fn_func_derive_peer_id_from_ed25519_pubkey.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_spoke_connect_fn_func_derive_peer_id_from_ed25519_pubkey.restype = _UniffiRustBuffer
_UniffiLib.uniffi_spoke_connect_fn_func_dispatch_allowed.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_spoke_connect_fn_func_dispatch_allowed.restype = ctypes.c_int8
_UniffiLib.uniffi_spoke_connect_fn_func_is_allowlisted.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_spoke_connect_fn_func_is_allowlisted.restype = ctypes.c_int8
_UniffiLib.uniffi_spoke_connect_fn_func_protocol_version.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_spoke_connect_fn_func_protocol_version.restype = ctypes.c_uint64
_UniffiLib.uniffi_spoke_connect_fn_func_required_capability.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_spoke_connect_fn_func_required_capability.restype = _UniffiRustBuffer
_UniffiLib.uniffi_spoke_connect_fn_func_sign_hello_ed25519.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_spoke_connect_fn_func_sign_hello_ed25519.restype = _UniffiRustBuffer
_UniffiLib.uniffi_spoke_connect_fn_func_verify_hello_ed25519.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_spoke_connect_fn_func_verify_hello_ed25519.restype = None
_UniffiLib.uniffi_spoke_connect_fn_method_inboundsequence_advance.argtypes = (
    ctypes.c_uint64,
    ctypes.c_int64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_spoke_connect_fn_method_inboundsequence_advance.restype = ctypes.c_uint64
_UniffiLib.uniffi_spoke_connect_fn_constructor_inboundsequence_new.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_spoke_connect_fn_constructor_inboundsequence_new.restype = ctypes.c_uint64
_UniffiLib.uniffi_spoke_connect_fn_method_noncestore_check_and_record.argtypes = (
    ctypes.c_uint64,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_spoke_connect_fn_method_noncestore_check_and_record.restype = ctypes.c_int8
_UniffiLib.uniffi_spoke_connect_fn_constructor_noncestore_new.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_spoke_connect_fn_constructor_noncestore_new.restype = ctypes.c_uint64
_UniffiLib.uniffi_spoke_connect_fn_method_outboundsequence_allocate.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_spoke_connect_fn_method_outboundsequence_allocate.restype = ctypes.c_uint64
_UniffiLib.uniffi_spoke_connect_fn_constructor_outboundsequence_new.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_spoke_connect_fn_constructor_outboundsequence_new.restype = ctypes.c_uint64
_UniffiLib.uniffi_spoke_connect_fn_clone_inboundsequence.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_spoke_connect_fn_clone_inboundsequence.restype = ctypes.c_uint64
_UniffiLib.uniffi_spoke_connect_fn_free_inboundsequence.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_spoke_connect_fn_free_inboundsequence.restype = None
_UniffiLib.uniffi_spoke_connect_fn_clone_noncestore.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_spoke_connect_fn_clone_noncestore.restype = ctypes.c_uint64
_UniffiLib.uniffi_spoke_connect_fn_free_noncestore.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_spoke_connect_fn_free_noncestore.restype = None
_UniffiLib.uniffi_spoke_connect_fn_clone_outboundsequence.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_spoke_connect_fn_clone_outboundsequence.restype = ctypes.c_uint64
_UniffiLib.uniffi_spoke_connect_fn_free_outboundsequence.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_spoke_connect_fn_free_outboundsequence.restype = None

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)



# Public interface members begin here.


class _UniffiFfiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()



# CoreError
# We want to define each variant as a nested class that's also a subclass,
# which is tricky in Python.  To accomplish this we're going to create each
# class separately, then manually add the child classes to the base class's
# __dict__.  All of this happens in dummy class to avoid polluting the module
# namespace.
class CoreError(Exception):
    """
    FFI-facing mirror of [`crate::core::CoreError`] (hello-gate / identity
    failures). Mapped 1:1 in [`From<CoreErrorImpl>`].
"""
    pass

_UniffiTempCoreError = CoreError

class CoreError:  # type: ignore
    """
    FFI-facing mirror of [`crate::core::CoreError`] (hello-gate / identity
    failures). Mapped 1:1 in [`From<CoreErrorImpl>`].
"""
    
    class InvalidHelloSignature(_UniffiTempCoreError):
        """
        The hello signature did not verify against the peer's public key (or
        the signature is not valid base64url / not 64 bytes).
"""
        
        def __init__(self):
            pass

        def __repr__(self):
            return "CoreError.InvalidHelloSignature({})".format(str(self))
    _UniffiTempCoreError.InvalidHelloSignature = InvalidHelloSignature # type: ignore
    class NonceReplay(_UniffiTempCoreError):
        """
        The `(peer_id, nonce)` pair was already accepted.
"""
        
        def __init__(self):
            pass

        def __repr__(self):
            return "CoreError.NonceReplay({})".format(str(self))
    _UniffiTempCoreError.NonceReplay = NonceReplay # type: ignore
    class HandshakeFailed(_UniffiTempCoreError):
        """
        Handshake-level failure (protocol version, peer id binding, …).
"""
        
        def __init__(self, reason):
            super().__init__(", ".join([
                "reason={!r}".format(reason),
            ]))
            self.reason = reason

        def __repr__(self):
            return "CoreError.HandshakeFailed({})".format(str(self))
    _UniffiTempCoreError.HandshakeFailed = HandshakeFailed # type: ignore
    class InvalidNonce(_UniffiTempCoreError):
        """
        The hello nonce does not satisfy the wire constraints (minLength 16).
"""
        
        def __init__(self, message):
            super().__init__(", ".join([
                "message={!r}".format(message),
            ]))
            self.message = message

        def __repr__(self):
            return "CoreError.InvalidNonce({})".format(str(self))
    _UniffiTempCoreError.InvalidNonce = InvalidNonce # type: ignore
    class Crypto(_UniffiTempCoreError):
        """
        Cryptography-level failure (invalid key bytes, base64 decoding, …).
"""
        
        def __init__(self, message):
            super().__init__(", ".join([
                "message={!r}".format(message),
            ]))
            self.message = message

        def __repr__(self):
            return "CoreError.Crypto({})".format(str(self))
    _UniffiTempCoreError.Crypto = Crypto # type: ignore
    class Jcs(_UniffiTempCoreError):
        """
        RFC 8785 JCS canonicalization / serialization of the signed object
        failed.
"""
        
        def __init__(self, message):
            super().__init__(", ".join([
                "message={!r}".format(message),
            ]))
            self.message = message

        def __repr__(self):
            return "CoreError.Jcs({})".format(str(self))
    _UniffiTempCoreError.Jcs = Jcs # type: ignore
    class TokenInvalid(_UniffiTempCoreError):
        """
        A capability-token proof failed validation (malformed shape, bad
        signature, untrusted issuer, subject/audience/expiry mismatch, or
        claim-rule violation).
"""
        
        def __init__(self, message):
            super().__init__(", ".join([
                "message={!r}".format(message),
            ]))
            self.message = message

        def __repr__(self):
            return "CoreError.TokenInvalid({})".format(str(self))
    _UniffiTempCoreError.TokenInvalid = TokenInvalid # type: ignore

CoreError = _UniffiTempCoreError # type: ignore
del _UniffiTempCoreError


class _UniffiFfiConverterTypeCoreError(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return CoreError.InvalidHelloSignature(
            )
        if variant == 2:
            return CoreError.NonceReplay(
            )
        if variant == 3:
            return CoreError.HandshakeFailed(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 4:
            return CoreError.InvalidNonce(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 5:
            return CoreError.Crypto(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 6:
            return CoreError.Jcs(
                _UniffiFfiConverterString.read(buf),
            )
        if variant == 7:
            return CoreError.TokenInvalid(
                _UniffiFfiConverterString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if isinstance(value, CoreError.InvalidHelloSignature):
            return
        if isinstance(value, CoreError.NonceReplay):
            return
        if isinstance(value, CoreError.HandshakeFailed):
            _UniffiFfiConverterString.check_lower(value.reason)
            return
        if isinstance(value, CoreError.InvalidNonce):
            _UniffiFfiConverterString.check_lower(value.message)
            return
        if isinstance(value, CoreError.Crypto):
            _UniffiFfiConverterString.check_lower(value.message)
            return
        if isinstance(value, CoreError.Jcs):
            _UniffiFfiConverterString.check_lower(value.message)
            return
        if isinstance(value, CoreError.TokenInvalid):
            _UniffiFfiConverterString.check_lower(value.message)
            return

    @staticmethod
    def write(value, buf):
        if isinstance(value, CoreError.InvalidHelloSignature):
            buf.write_i32(1)
        if isinstance(value, CoreError.NonceReplay):
            buf.write_i32(2)
        if isinstance(value, CoreError.HandshakeFailed):
            buf.write_i32(3)
            _UniffiFfiConverterString.write(value.reason, buf)
        if isinstance(value, CoreError.InvalidNonce):
            buf.write_i32(4)
            _UniffiFfiConverterString.write(value.message, buf)
        if isinstance(value, CoreError.Crypto):
            buf.write_i32(5)
            _UniffiFfiConverterString.write(value.message, buf)
        if isinstance(value, CoreError.Jcs):
            buf.write_i32(6)
            _UniffiFfiConverterString.write(value.message, buf)
        if isinstance(value, CoreError.TokenInvalid):
            buf.write_i32(7)
            _UniffiFfiConverterString.write(value.message, buf)

class _UniffiFfiConverterUInt64(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u64"
    VALUE_MIN = 0
    VALUE_MAX = 2**64

    @staticmethod
    def read(buf):
        return buf.read_u64()

    @staticmethod
    def write(value, buf):
        buf.write_u64(value)

class _UniffiFfiConverterInt64(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "i64"
    VALUE_MIN = -2**63
    VALUE_MAX = 2**63

    @staticmethod
    def read(buf):
        return buf.read_i64()

    @staticmethod
    def write(value, buf):
        buf.write_i64(value)



# CoreInvokeError
# We want to define each variant as a nested class that's also a subclass,
# which is tricky in Python.  To accomplish this we're going to create each
# class separately, then manually add the child classes to the base class's
# __dict__.  All of this happens in dummy class to avoid polluting the module
# namespace.
class CoreInvokeError(Exception):
    """
    FFI-facing mirror of [`crate::core::CoreInvokeError`] (invoke-path
    sequence / correlation failures). Mapped 1:1 in
    [`From<CoreInvokeErrorImpl>`].
"""
    pass

_UniffiTempCoreInvokeError = CoreInvokeError

class CoreInvokeError:  # type: ignore
    """
    FFI-facing mirror of [`crate::core::CoreInvokeError`] (invoke-path
    sequence / correlation failures). Mapped 1:1 in
    [`From<CoreInvokeErrorImpl>`].
"""
    
    class SequenceExhausted(_UniffiTempCoreInvokeError):
        """
        The session's outbound sequence space (2⁵³−1) is exhausted; the
        session must be closed and reopened — sequences never wrap.
"""
        
        def __init__(self):
            pass

        def __repr__(self):
            return "CoreInvokeError.SequenceExhausted({})".format(str(self))
    _UniffiTempCoreInvokeError.SequenceExhausted = SequenceExhausted # type: ignore
    class InboundSequenceMismatch(_UniffiTempCoreInvokeError):
        """
        An inbound invoke `sequence` is not the next expected one (replay or
        out-of-order); the invoke must not be dispatched.
"""
        
        def __init__(self, expected, actual):
            super().__init__(", ".join([
                "expected={!r}".format(expected),
                "actual={!r}".format(actual),
            ]))
            self.expected = expected
            self.actual = actual

        def __repr__(self):
            return "CoreInvokeError.InboundSequenceMismatch({})".format(str(self))
    _UniffiTempCoreInvokeError.InboundSequenceMismatch = InboundSequenceMismatch # type: ignore
    class CorrelationMismatch(_UniffiTempCoreInvokeError):
        """
        A response did not echo the request's `session_id` / `sequence` /
        `request_id`.
"""
        
        def __init__(self):
            pass

        def __repr__(self):
            return "CoreInvokeError.CorrelationMismatch({})".format(str(self))
    _UniffiTempCoreInvokeError.CorrelationMismatch = CorrelationMismatch # type: ignore

CoreInvokeError = _UniffiTempCoreInvokeError # type: ignore
del _UniffiTempCoreInvokeError


class _UniffiFfiConverterTypeCoreInvokeError(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return CoreInvokeError.SequenceExhausted(
            )
        if variant == 2:
            return CoreInvokeError.InboundSequenceMismatch(
                _UniffiFfiConverterUInt64.read(buf),
                _UniffiFfiConverterInt64.read(buf),
            )
        if variant == 3:
            return CoreInvokeError.CorrelationMismatch(
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if isinstance(value, CoreInvokeError.SequenceExhausted):
            return
        if isinstance(value, CoreInvokeError.InboundSequenceMismatch):
            _UniffiFfiConverterUInt64.check_lower(value.expected)
            _UniffiFfiConverterInt64.check_lower(value.actual)
            return
        if isinstance(value, CoreInvokeError.CorrelationMismatch):
            return

    @staticmethod
    def write(value, buf):
        if isinstance(value, CoreInvokeError.SequenceExhausted):
            buf.write_i32(1)
        if isinstance(value, CoreInvokeError.InboundSequenceMismatch):
            buf.write_i32(2)
            _UniffiFfiConverterUInt64.write(value.expected, buf)
            _UniffiFfiConverterInt64.write(value.actual, buf)
        if isinstance(value, CoreInvokeError.CorrelationMismatch):
            buf.write_i32(3)


class InboundSequenceProtocol(typing.Protocol):
    """
    Inbound sequence expectation — thread-safe FFI wrapper over the core
    expectation, starting at 0.
"""
    
    def advance(self, sequence: int) -> int:
        """
        Accepts `sequence` iff it equals the next expected inbound sequence;
        on acceptance the expectation advances by 1 and the new expectation
        is returned. A replayed or out-of-order sequence yields
        `InboundSequenceMismatch` and the expectation is left unchanged — the
        caller must reject the invoke without dispatching it.
"""
        raise NotImplementedError

class InboundSequence(InboundSequenceProtocol):
    """
    Inbound sequence expectation — thread-safe FFI wrapper over the core
    expectation, starting at 0.
"""
    
    _handle: ctypes.c_uint64
    def __init__(self, ):
        """
        Creates an expectation starting at 0 (the first accepted sequence).
"""
        _uniffi_lowered_args = (
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeInboundSequence.lift
        _uniffi_error_converter = None
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_spoke_connect_fn_constructor_inboundsequence_new,
            *_uniffi_lowered_args,
        )
        self._handle = _uniffi_ffi_result

    def __del__(self):
        # In case of partial initialization of instances.
        handle = getattr(self, "_handle", None)
        if handle is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_spoke_connect_fn_free_inboundsequence, handle)

    def _uniffi_clone_handle(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_spoke_connect_fn_clone_inboundsequence, self._handle)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _uniffi_make_instance(cls, handle):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required handle.
        inst = cls.__new__(cls)
        inst._handle = handle
        return inst
    def advance(self, sequence: int) -> int:
        """
        Accepts `sequence` iff it equals the next expected inbound sequence;
        on acceptance the expectation advances by 1 and the new expectation
        is returned. A replayed or out-of-order sequence yields
        `InboundSequenceMismatch` and the expectation is left unchanged — the
        caller must reject the invoke without dispatching it.
"""
        
        _UniffiFfiConverterInt64.check_lower(sequence)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterInt64.lower(sequence),
        )
        _uniffi_lift_return = _UniffiFfiConverterUInt64.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeCoreInvokeError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_spoke_connect_fn_method_inboundsequence_advance,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)





class _UniffiFfiConverterTypeInboundSequence:
    @staticmethod
    def lift(value: int) -> InboundSequence:
        return InboundSequence._uniffi_make_instance(value)

    @staticmethod
    def check_lower(value: InboundSequence):
        if not isinstance(value, InboundSequence):
            raise TypeError("Expected InboundSequence instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: InboundSequence) -> ctypes.c_uint64:
        return value._uniffi_clone_handle()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer) -> InboundSequence:
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw handle value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: InboundSequence, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))

class _UniffiFfiConverterBoolean:
    @classmethod
    def check_lower(cls, value):
        return not not value

    @classmethod
    def lower(cls, value):
        return 1 if value else 0

    @staticmethod
    def lift(value):
        return value != 0

    @classmethod
    def read(cls, buf):
        return cls.lift(buf.read_u8())

    @classmethod
    def write(cls, value, buf):
        buf.write_u8(value)


class NonceStoreProtocol(typing.Protocol):
    """
    Single-use `(peer_id, nonce)` replay store — thread-safe FFI wrapper over
    the core store.
"""
    
    def check_and_record(self, peer_id: str,nonce: str) -> bool:
        """
        Records `(peer_id, nonce)` unless it was already accepted; returns
        `false` on replay. Call only after the hello passed every earlier
        gate (allowlist, signature) so a rejected hello is not burned.
"""
        raise NotImplementedError

class NonceStore(NonceStoreProtocol):
    """
    Single-use `(peer_id, nonce)` replay store — thread-safe FFI wrapper over
    the core store.
"""
    
    _handle: ctypes.c_uint64
    def __init__(self, ):
        """
        Creates an empty store.
"""
        _uniffi_lowered_args = (
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeNonceStore.lift
        _uniffi_error_converter = None
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_spoke_connect_fn_constructor_noncestore_new,
            *_uniffi_lowered_args,
        )
        self._handle = _uniffi_ffi_result

    def __del__(self):
        # In case of partial initialization of instances.
        handle = getattr(self, "_handle", None)
        if handle is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_spoke_connect_fn_free_noncestore, handle)

    def _uniffi_clone_handle(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_spoke_connect_fn_clone_noncestore, self._handle)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _uniffi_make_instance(cls, handle):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required handle.
        inst = cls.__new__(cls)
        inst._handle = handle
        return inst
    def check_and_record(self, peer_id: str,nonce: str) -> bool:
        """
        Records `(peer_id, nonce)` unless it was already accepted; returns
        `false` on replay. Call only after the hello passed every earlier
        gate (allowlist, signature) so a rejected hello is not burned.
"""
        
        _UniffiFfiConverterString.check_lower(peer_id)

        _UniffiFfiConverterString.check_lower(nonce)
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
            _UniffiFfiConverterString.lower(peer_id),
            _UniffiFfiConverterString.lower(nonce),
        )
        _uniffi_lift_return = _UniffiFfiConverterBoolean.lift
        _uniffi_error_converter = None
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_spoke_connect_fn_method_noncestore_check_and_record,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)





class _UniffiFfiConverterTypeNonceStore:
    @staticmethod
    def lift(value: int) -> NonceStore:
        return NonceStore._uniffi_make_instance(value)

    @staticmethod
    def check_lower(value: NonceStore):
        if not isinstance(value, NonceStore):
            raise TypeError("Expected NonceStore instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: NonceStore) -> ctypes.c_uint64:
        return value._uniffi_clone_handle()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer) -> NonceStore:
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw handle value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: NonceStore, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))


class OutboundSequenceProtocol(typing.Protocol):
    """
    Outbound sequence counter — thread-safe FFI wrapper over the core
    counter, starting at 0.
"""
    
    def allocate(self, ) -> int:
        """
        Assigns the next outbound sequence; on exhaustion (past the JSON-safe
        wire maximum) `SequenceExhausted` is returned and the counter stays
        exhausted — sequences never wrap. The caller must close the session.
"""
        raise NotImplementedError

class OutboundSequence(OutboundSequenceProtocol):
    """
    Outbound sequence counter — thread-safe FFI wrapper over the core
    counter, starting at 0.
"""
    
    _handle: ctypes.c_uint64
    def __init__(self, ):
        """
        Creates a counter starting at 0 (the first allocate returns 0).
"""
        _uniffi_lowered_args = (
        )
        _uniffi_lift_return = _UniffiFfiConverterTypeOutboundSequence.lift
        _uniffi_error_converter = None
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_spoke_connect_fn_constructor_outboundsequence_new,
            *_uniffi_lowered_args,
        )
        self._handle = _uniffi_ffi_result

    def __del__(self):
        # In case of partial initialization of instances.
        handle = getattr(self, "_handle", None)
        if handle is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_spoke_connect_fn_free_outboundsequence, handle)

    def _uniffi_clone_handle(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_spoke_connect_fn_clone_outboundsequence, self._handle)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _uniffi_make_instance(cls, handle):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required handle.
        inst = cls.__new__(cls)
        inst._handle = handle
        return inst
    def allocate(self, ) -> int:
        """
        Assigns the next outbound sequence; on exhaustion (past the JSON-safe
        wire maximum) `SequenceExhausted` is returned and the counter stays
        exhausted — sequences never wrap. The caller must close the session.
"""
        _uniffi_lowered_args = (
            self._uniffi_clone_handle(),
        )
        _uniffi_lift_return = _UniffiFfiConverterUInt64.lift
        _uniffi_error_converter = _UniffiFfiConverterTypeCoreInvokeError
        _uniffi_ffi_result = _uniffi_rust_call_with_error(
            _uniffi_error_converter,
            _UniffiLib.uniffi_spoke_connect_fn_method_outboundsequence_allocate,
            *_uniffi_lowered_args,
        )
        return _uniffi_lift_return(_uniffi_ffi_result)





class _UniffiFfiConverterTypeOutboundSequence:
    @staticmethod
    def lift(value: int) -> OutboundSequence:
        return OutboundSequence._uniffi_make_instance(value)

    @staticmethod
    def check_lower(value: OutboundSequence):
        if not isinstance(value, OutboundSequence):
            raise TypeError("Expected OutboundSequence instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: OutboundSequence) -> ctypes.c_uint64:
        return value._uniffi_clone_handle()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer) -> OutboundSequence:
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw handle value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: OutboundSequence, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))

class _UniffiFfiConverterBytes(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative byte string length")
        return buf.read(size)

    @staticmethod
    def check_lower(value):
        try:
            memoryview(value)
        except TypeError:
            raise TypeError("a bytes-like object is required, not {!r}".format(type(value).__name__))

    @staticmethod
    def write(value, buf):
        buf.write_i32(len(value))
        buf.write(value)

class _UniffiFfiConverterSequenceString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiFfiConverterString.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiFfiConverterString.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiFfiConverterString.read(buf) for i in range(count)
        ]

class _UniffiFfiConverterOptionalString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiFfiConverterString.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiFfiConverterString.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiFfiConverterString.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")
def check_response_correlation(expected_session_id: str,expected_sequence: int,expected_request_id: str,actual_session_id: str,actual_sequence: int,actual_request_id: str) -> None:
    """
    Checks that a response echoes the request's `session_id` / `sequence` /
    `request_id` — the three echo fields, flattened to primitives.
"""
    
    _UniffiFfiConverterString.check_lower(expected_session_id)

    _UniffiFfiConverterUInt64.check_lower(expected_sequence)

    _UniffiFfiConverterString.check_lower(expected_request_id)

    _UniffiFfiConverterString.check_lower(actual_session_id)

    _UniffiFfiConverterUInt64.check_lower(actual_sequence)

    _UniffiFfiConverterString.check_lower(actual_request_id)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(expected_session_id),
        _UniffiFfiConverterUInt64.lower(expected_sequence),
        _UniffiFfiConverterString.lower(expected_request_id),
        _UniffiFfiConverterString.lower(actual_session_id),
        _UniffiFfiConverterUInt64.lower(actual_sequence),
        _UniffiFfiConverterString.lower(actual_request_id),
    )
    _uniffi_lift_return = lambda val: None
    _uniffi_error_converter = _UniffiFfiConverterTypeCoreInvokeError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_spoke_connect_fn_func_check_response_correlation,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def derive_peer_id_from_ed25519_pubkey(pubkey: bytes) -> str:
    """
    Derive the wire `peer_id` string for a 32-byte Ed25519 public key.

    The result matches rust-libp2p `PeerId::to_string()` for the same key
    (locked by the golden-vector tests).
"""
    
    _UniffiFfiConverterBytes.check_lower(pubkey)
    _uniffi_lowered_args = (
        _UniffiFfiConverterBytes.lower(pubkey),
    )
    _uniffi_lift_return = _UniffiFfiConverterString.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeCoreError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_spoke_connect_fn_func_derive_peer_id_from_ed25519_pubkey,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def dispatch_allowed(op: str,negotiated_capabilities: typing.List[str]) -> bool:
    """
    Whether `op` may be dispatched in a session with
    `negotiated_capabilities`. Fails closed: an unknown `op` has no core-table
    requirement and is not authorized by this gate (hosts answer
    `op_unsupported`).
"""
    
    _UniffiFfiConverterString.check_lower(op)

    _UniffiFfiConverterSequenceString.check_lower(negotiated_capabilities)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(op),
        _UniffiFfiConverterSequenceString.lower(negotiated_capabilities),
    )
    _uniffi_lift_return = _UniffiFfiConverterBoolean.lift
    _uniffi_error_converter = None
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_spoke_connect_fn_func_dispatch_allowed,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def is_allowlisted(allowlist: typing.List[str],peer_id: str) -> bool:
    """
    Whether `peer_id` is on the allowlist. Fails closed: an empty allowlist
    rejects every peer.
"""
    
    _UniffiFfiConverterSequenceString.check_lower(allowlist)

    _UniffiFfiConverterString.check_lower(peer_id)
    _uniffi_lowered_args = (
        _UniffiFfiConverterSequenceString.lower(allowlist),
        _UniffiFfiConverterString.lower(peer_id),
    )
    _uniffi_lift_return = _UniffiFfiConverterBoolean.lift
    _uniffi_error_converter = None
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_spoke_connect_fn_func_is_allowlisted,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def protocol_version() -> int:
    """
    The connect protocol version exchanged in `ConnectHello` (protocol
    version 1 is current).
"""
    _uniffi_lowered_args = (
    )
    _uniffi_lift_return = _UniffiFfiConverterUInt64.lift
    _uniffi_error_converter = None
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_spoke_connect_fn_func_protocol_version,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def required_capability(op: str) -> typing.Optional[str]:
    """
    The capability required to dispatch `op`, per the protocol v1 core-op
    table; `None` for product-defined ops.
"""
    
    _UniffiFfiConverterString.check_lower(op)
    _uniffi_lowered_args = (
        _UniffiFfiConverterString.lower(op),
    )
    _uniffi_lift_return = _UniffiFfiConverterOptionalString.lift
    _uniffi_error_converter = None
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_spoke_connect_fn_func_required_capability,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def sign_hello_ed25519(secret: bytes,nonce: str,host_json: str) -> str:
    """
    Sign a hello with a raw Ed25519 secret key (32 bytes), returning the
    signed `ConnectHello` envelope as a JSON string.

    `nonce` must meet the wire floor (minLength 16). `host_json` is the
    canonical JSON of the `HostCapabilityManifest` embedded in
    `ConnectHello.host`.
"""
    
    _UniffiFfiConverterBytes.check_lower(secret)

    _UniffiFfiConverterString.check_lower(nonce)

    _UniffiFfiConverterString.check_lower(host_json)
    _uniffi_lowered_args = (
        _UniffiFfiConverterBytes.lower(secret),
        _UniffiFfiConverterString.lower(nonce),
        _UniffiFfiConverterString.lower(host_json),
    )
    _uniffi_lift_return = _UniffiFfiConverterString.lift
    _uniffi_error_converter = _UniffiFfiConverterTypeCoreError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_spoke_connect_fn_func_sign_hello_ed25519,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)
def verify_hello_ed25519(public_key: bytes,expected_peer_id: str,hello_json: str) -> None:
    """
    Verify a received hello against a 32-byte Ed25519 public key.

    `expected_peer_id` is the authenticated remote peer; `hello_json` is the
    JSON string of the received `ConnectHello` envelope. Fails on protocol
    version mismatch, public-key / peer-id binding mismatch, or an invalid
    signature.
"""
    
    _UniffiFfiConverterBytes.check_lower(public_key)

    _UniffiFfiConverterString.check_lower(expected_peer_id)

    _UniffiFfiConverterString.check_lower(hello_json)
    _uniffi_lowered_args = (
        _UniffiFfiConverterBytes.lower(public_key),
        _UniffiFfiConverterString.lower(expected_peer_id),
        _UniffiFfiConverterString.lower(hello_json),
    )
    _uniffi_lift_return = lambda val: None
    _uniffi_error_converter = _UniffiFfiConverterTypeCoreError
    _uniffi_ffi_result = _uniffi_rust_call_with_error(
        _uniffi_error_converter,
        _UniffiLib.uniffi_spoke_connect_fn_func_verify_hello_ed25519,
        *_uniffi_lowered_args,
    )
    return _uniffi_lift_return(_uniffi_ffi_result)

__all__ = [
    "InternalError",
    "CoreError",
    "CoreInvokeError",
    "check_response_correlation",
    "derive_peer_id_from_ed25519_pubkey",
    "dispatch_allowed",
    "is_allowlisted",
    "protocol_version",
    "required_capability",
    "sign_hello_ed25519",
    "verify_hello_ed25519",
    "InboundSequence",
    "InboundSequenceProtocol",
    "NonceStore",
    "NonceStoreProtocol",
    "OutboundSequence",
    "OutboundSequenceProtocol",
]