/**
 * Noise XX state machine gate — canonical cacophony test vector
 * (Task 2 of connect-ts-noise-stack).
 *
 * Vector source: noise-c `tests/vector/cacophony.txt` (generated by the
 * cacophony project — the vector set the Noise protocol spec points to),
 * entry `Noise_XX_25519_ChaChaPoly_SHA256`. The entry below was extracted
 * verbatim (keys, prologue, and all six messages: 3 handshake flights +
 * 3 post-split transport messages).
 *
 * The vector pins, transitively:
 *   - the `e` token in non-PSK XX does MixHash only (flight 1 payload is
 *     carried in the clear — current Noise spec §5.3, matching snow and
 *     noise-c; MixKey(e.pub) is a PSK-only rule),
 *   - the `s` token is EncryptAndHash'ed with AAD = handshake hash,
 *   - handshake AEAD nonces continue across flights (flight 3's `s` uses
 *     the nonce left over from flight 2's payload),
 *   - Split() = HKDF(ck, empty, 2×32) → initiator encrypts with the first
 *     output, decrypts with the second (mirrored for the responder),
 *   - transport frames use AAD = empty and per-direction nonces from 0.
 *
 * Both parties must derive the same handshake hash `h` and the same split
 * transport keys; the last three message ciphertexts cannot match unless
 * the full ck/h chain is right.
 */
import { describe, expect, it } from "vitest";

import { decrypt, encrypt, getPublicKey } from "../../src/noise/crypto.js";
import { NoiseXX } from "../../src/noise/xx.js";
import { fromHex, toHex } from "../hex.js";

// ── Canonical cacophony vector: Noise_XX_25519_ChaChaPoly_SHA256 ───────────

const CACOPHONY_XX = {
  prologue: fromHex("4a6f686e2047616c74"),
  initStaticPrivate: fromHex("e61ef9919cde45dd5f82166404bd08e38bceb5dfdfded0a34c8df7ed542214d1"),
  initEphemeralPrivate: fromHex("893e28b9dc6ca8d611ab664754b8ceb7bac5117349a4439a6b0569da977c464a"),
  respStaticPrivate: fromHex("4a3acbfdb163dec651dfa3194dece676d437029c62a408b4c5ea9114246e4893"),
  respEphemeralPrivate: fromHex("bbdb4cdbd309f1a1f2e1456967fe288cadd6f712d65dc7b7793d5e63da6b375b"),
  messages: [
    { payload: fromHex("4c756477696720766f6e204d69736573"), ciphertext: fromHex("ca35def5ae56cec33dc2036731ab14896bc4c75dbb07a61f879f8e3afa4c79444c756477696720766f6e204d69736573") },
    { payload: fromHex("4d757272617920526f746862617264"), ciphertext: fromHex("95ebc60d2b1fa672c1f46a8aa265ef51bfe38e7ccb39ec5be34069f14480884381cbad1f276e038c48378ffce2b65285e08d6b68aaa3629a5a8639392490e5b9bd5269c2f1e4f488ed8831161f19b7815528f8982ffe09be9b5c412f8a0db50f8814c7194e83f23dbd8d162c9326ad") },
    { payload: fromHex("462e20412e20486179656b"), ciphertext: fromHex("c7195ffacac1307ff99046f219750fc47693e23c3cb08b89c2af808b444850a80ae475b9df0f169ae80a89be0865b57f58c9fea0d4ec82a286427402f113e4b6ae769a1d95941d49b25030") },
    { payload: fromHex("4361726c204d656e676572"), ciphertext: fromHex("96763ed773f8e47bb3712f0e29b3060ffc956ffc146cee53d5e1df") },
    { payload: fromHex("4a65616e2d426170746973746520536179"), ciphertext: fromHex("3e40f15f6f3a46ae446b253bf8b1d9ffb6ed9b174d272328ff91a7e2e5c79c07f5") },
    { payload: fromHex("457567656e2042f6686d20766f6e2042617765726b"), ciphertext: fromHex("eb3f3515110702e047a6c9da4478b6ead94873c11c0f2d710ddb3f09fce024b3a58502ae3f") },
  ],
};

function makeVectorHandshake() {
  const initiator = new NoiseXX({
    initiator: true,
    staticKeyPair: { privateKey: CACOPHONY_XX.initStaticPrivate },
    ephemeralKeyPair: { privateKey: CACOPHONY_XX.initEphemeralPrivate },
    prologue: CACOPHONY_XX.prologue,
  });
  const responder = new NoiseXX({
    initiator: false,
    staticKeyPair: { privateKey: CACOPHONY_XX.respStaticPrivate },
    ephemeralKeyPair: { privateKey: CACOPHONY_XX.respEphemeralPrivate },
    prologue: CACOPHONY_XX.prologue,
  });
  return { initiator, responder };
}

/** Drive the full interleaved vector exchange (write → read alternation). */
function runCacophonyHandshake() {
  const { initiator, responder } = makeVectorHandshake();
  const [m1, m2, m3] = CACOPHONY_XX.messages;
  const flight1 = initiator.writeMessage(m1.payload);
  const read1 = responder.readMessage(flight1);
  const flight2 = responder.writeMessage(m2.payload);
  const read2 = initiator.readMessage(flight2);
  const flight3 = initiator.writeMessage(m3.payload);
  const read3 = responder.readMessage(flight3);
  return { initiator, responder, flight1, flight2, flight3, read1, read2, read3 };
}

describe("NoiseXX against the canonical cacophony vector", () => {
  it("reproduces the three handshake flight ciphertexts byte-for-byte", () => {
    const { flight1, flight2, flight3 } = runCacophonyHandshake();
    const [m1, m2, m3] = CACOPHONY_XX.messages;

    // Flight 1: -> e  (I → R). Payload rides in the clear (k empty).
    expect(toHex(flight1)).toBe(toHex(m1.ciphertext));
    // Flight 2: <- e, ee, s, es  (R → I).
    expect(toHex(flight2)).toBe(toHex(m2.ciphertext));
    // Flight 3: -> s, se  (I → R).
    expect(toHex(flight3)).toBe(toHex(m3.ciphertext));
  });

  it("recovers the vector plaintext payloads on every read", () => {
    const { read1, read2, read3 } = runCacophonyHandshake();
    const [m1, m2, m3] = CACOPHONY_XX.messages;
    expect(toHex(read1)).toBe(toHex(m1.payload));
    expect(toHex(read2)).toBe(toHex(m2.payload));
    expect(toHex(read3)).toBe(toHex(m3.payload));
  });

  it("derives the same handshake hash on both parties", () => {
    const { initiator, responder } = runCacophonyHandshake();
    expect(toHex(initiator.finish().handshakeHash)).toBe(
      toHex(responder.finish().handshakeHash),
    );
  });

  it("derives the same split transport keys on both parties", () => {
    const { initiator, responder } = runCacophonyHandshake();
    const init = initiator.finish();
    const resp = responder.finish();

    // Initiator encrypts with the first Split output, decrypts with the
    // second; the responder mirrors (Noise spec §5.2 Split semantics).
    expect(toHex(init.tx)).toBe(toHex(resp.rx));
    expect(toHex(init.rx)).toBe(toHex(resp.tx));
  });

  it("exposes the remote static public key on both parties", () => {
    const { initiator, responder } = runCacophonyHandshake();
    expect(toHex(initiator.finish().remoteStaticPublic)).toBe(
      toHex(getPublicKey(CACOPHONY_XX.respStaticPrivate)),
    );
    expect(toHex(responder.finish().remoteStaticPublic)).toBe(
      toHex(getPublicKey(CACOPHONY_XX.initStaticPrivate)),
    );
  });

  it("reproduces the post-split transport ciphertexts with the split keys", () => {
    const { initiator, responder } = runCacophonyHandshake();
    const init = initiator.finish();
    const resp = responder.finish();
    const [, , , t1, t2, t3] = CACOPHONY_XX.messages;
    const emptyAad = new Uint8Array(0);

    // The vector's transport phase alternates turns with the RESPONDER
    // sending first (the initiator wrote flight 3, so it is the
    // responder's turn — noise-c test-vector.c driver convention):
    //   t1 = responder → initiator (resp tx / c2, nonce 0)
    //   t2 = initiator → responder (init tx / c1, nonce 0)
    //   t3 = responder → initiator (resp tx / c2, nonce 1)
    expect(toHex(encrypt(resp.tx, 0, emptyAad, t1.payload))).toBe(
      toHex(t1.ciphertext),
    );
    expect(toHex(encrypt(init.tx, 0, emptyAad, t2.payload))).toBe(
      toHex(t2.ciphertext),
    );
    expect(toHex(encrypt(resp.tx, 1, emptyAad, t3.payload))).toBe(
      toHex(t3.ciphertext),
    );

    // Cross-party open round-trips with the mirrored keys.
    expect(toHex(decrypt(init.rx, 0, emptyAad, t1.ciphertext)!)).toBe(
      toHex(t1.payload),
    );
    expect(toHex(decrypt(resp.rx, 0, emptyAad, t2.ciphertext)!)).toBe(
      toHex(t2.payload),
    );
    expect(toHex(decrypt(init.rx, 1, emptyAad, t3.ciphertext)!)).toBe(
      toHex(t3.payload),
    );
  });
});

// ── Production-path behaviors (random ephemerals, empty prologue) ───────────

describe("NoiseXX production path", () => {
  it("completes a full handshake with random ephemeral keys and empty prologue", () => {
    const initiator = new NoiseXX({
      initiator: true,
      staticKeyPair: { privateKey: CACOPHONY_XX.initStaticPrivate },
    });
    const responder = new NoiseXX({
      initiator: false,
      staticKeyPair: { privateKey: CACOPHONY_XX.respStaticPrivate },
    });

    const flight1 = initiator.writeMessage(new Uint8Array(0));
    expect(flight1).toHaveLength(32); // e.pub only; empty payload is clear
    expect(responder.readMessage(flight1)).toHaveLength(0);

    const flight2 = responder.writeMessage(new Uint8Array(0));
    expect(flight2).toHaveLength(32 + 48 + 16); // e + ct(s) + tag(empty)
    expect(initiator.readMessage(flight2)).toHaveLength(0);

    const flight3 = initiator.writeMessage(new Uint8Array(0));
    expect(flight3).toHaveLength(48 + 16); // ct(s) + tag(empty)
    expect(responder.readMessage(flight3)).toHaveLength(0);

    const init = initiator.finish();
    const resp = responder.finish();
    expect(toHex(init.handshakeHash)).toBe(toHex(resp.handshakeHash));
    expect(toHex(init.tx)).toBe(toHex(resp.rx));
    expect(toHex(init.rx)).toBe(toHex(resp.tx));

    // One sealed transport frame each way (empty AAD, nonce 0).
    const frame = new TextEncoder().encode("spoke-over-noise");
    const sealed = encrypt(init.tx, 0, new Uint8Array(0), frame);
    expect(sealed).toHaveLength(frame.length + 16);
    expect(toHex(decrypt(resp.rx, 0, new Uint8Array(0), sealed)!)).toBe(
      toHex(frame),
    );
  });

  it("rejects a tampered handshake flight on read", () => {
    const { initiator, responder } = makeVectorHandshake();
    const [m1, m2] = CACOPHONY_XX.messages;
    responder.readMessage(m1.ciphertext); // flight 1 is clear-text; fine
    const tampered = new Uint8Array(m2.ciphertext);
    tampered[40] ^= 0x01; // inside the encrypted `s` token
    initiator.writeMessage(m1.payload); // advance to flight 2 read
    expect(() => initiator.readMessage(tampered)).toThrow(); // AEAD failure
  });

  it("enforces the per-role message order", () => {
    const responder = new NoiseXX({
      initiator: false,
      staticKeyPair: { privateKey: CACOPHONY_XX.respStaticPrivate },
    });
    // Responder must read flight 1 before writing flight 2.
    expect(() => responder.writeMessage(new Uint8Array(0))).toThrow();
  });

  it("rejects a truncated handshake flight on read", () => {
    const { initiator, responder } = makeVectorHandshake();
    const [m1, m2] = CACOPHONY_XX.messages;
    responder.readMessage(m1.ciphertext);
    initiator.writeMessage(m1.payload); // advance to flight 2 read
    // Flight 2 needs 32 (e) + 48 (encrypted s) bytes before the payload;
    // cutting inside the s token must abort, not read garbage.
    expect(() => initiator.readMessage(m2.ciphertext.subarray(0, 70))).toThrow();
  });

  it("rejects finishing before the handshake is complete", () => {
    const initiator = new NoiseXX({
      initiator: true,
      staticKeyPair: { privateKey: CACOPHONY_XX.initStaticPrivate },
    });
    initiator.writeMessage(new Uint8Array(0));
    expect(() => initiator.finish()).toThrow();
  });
});
