//! Generate Rust types from SPOKE JSON Schemas using typify.

use glob::glob;
use schemars::schema::RootSchema;
use serde_json::Value;
use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process;
use typify::{TypeSpace, TypeSpaceSettings};

const EXPECTED_SCHEMA_COUNT: usize = 19;

struct GeneratedModule {
    rust_mod: String,
    rel_parent: PathBuf,
    export_all: bool,
    export_type: Option<String>,
}

fn repo_root() -> PathBuf {
    if let Ok(root) = env::var("SPOKE_REPO_ROOT") {
        return PathBuf::from(root);
    }
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../..")
        .canonicalize()
        .expect("repo root")
}

fn schemas_dir(root: &Path) -> PathBuf {
    if let Ok(dir) = env::var("SPOKE_SCHEMAS_DIR") {
        return PathBuf::from(dir);
    }
    root.join("schemas")
}

fn to_rust_module_name(base: &str) -> String {
    base.replace('-', "_")
}

fn source_schemas_dir(root: &Path) -> PathBuf {
    root.join("schemas")
}

fn export_mode_for_schema(schema_path: &Path) -> (bool, Option<String>) {
    let content = fs::read_to_string(schema_path).expect("read source schema");
    let raw: Value = serde_json::from_str(&content).expect("parse source schema");

    let title = raw.get("title").and_then(Value::as_str);

    // Mirror TS buildTypeScriptBarrelExport: single-word title wins over definitions-only
    // (oneOf/anyOf + definitions schemas like upsert-response export the title type only).
    if let Some(t) = title {
        if !t.contains(' ') {
            return (false, Some(t.to_string()));
        }
    }

    let has_definitions = raw.get("definitions").is_some() || raw.get("$defs").is_some();
    let has_object_body = raw.get("type") == Some(&Value::String("object".into()))
        || raw.get("properties").is_some();

    if has_definitions && !has_object_body {
        return (true, None);
    }

    (true, None)
}

fn write_mod_rs(dir: &Path, child_modules: &[String], generated: &[&GeneratedModule]) {
    let mut lines = vec![
        "//! AUTO-GENERATED FROM JSON SCHEMA - DO NOT MODIFY".to_string(),
        "//! Generated by: pnpm run codegen".to_string(),
        String::new(),
    ];

    for m in child_modules {
        lines.push(format!("pub mod {m};"));
    }
    for module in generated {
        lines.push(format!("pub mod {};", module.rust_mod));
    }
    lines.push(String::new());

    for m in child_modules {
        lines.push(format!("pub use {m}::*;"));
    }
    for module in generated {
        if module.export_all {
            lines.push(format!("pub use {}::*;", module.rust_mod));
        } else if let Some(type_name) = &module.export_type {
            lines.push(format!("pub use {}::{type_name};", module.rust_mod));
        }
    }
    lines.push(String::new());

    fs::write(dir.join("mod.rs"), lines.join("\n")).expect("write mod.rs");
}

fn generate_schema_rust(
    schema_path: &Path,
    schemas_dir: &Path,
    out_path: &Path,
) -> Result<(), String> {
    let content = fs::read_to_string(schema_path)
        .map_err(|err| format!("failed to read {}: {err}", schema_path.display()))?;
    let schema: RootSchema = serde_json::from_str(&content).map_err(|err| {
        format!(
            "invalid JSON Schema in {}: {err}",
            schema_path.display()
        )
    })?;

    let mut settings = TypeSpaceSettings::default();
    settings.with_struct_builder(true);

    let mut type_space = TypeSpace::new(&settings);

    let previous_dir = env::current_dir().ok();
    if let Some(parent) = schema_path.parent() {
        let _ = env::set_current_dir(parent);
    }

    let add_result = type_space.add_root_schema(schema);
    if let Some(prev) = previous_dir {
        let _ = env::set_current_dir(prev);
    }

    add_result.map_err(|err| {
        format!(
            "typify failed for {}: {err}",
            schema_path.display()
        )
    })?;

    let rust = type_space.to_stream().to_string();
    if rust.trim().is_empty() {
        return Err(format!(
            "typify produced empty output for {}",
            schema_path.display()
        ));
    }

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent).map_err(|err| {
            format!(
                "failed to create output directory {}: {err}",
                parent.display()
            )
        })?;
    }

    let header = format!(
        "//! AUTO-GENERATED FROM JSON SCHEMA - DO NOT MODIFY\n//! Source: {}\n//! Generated by: pnpm run codegen\n\n",
        schema_path
            .strip_prefix(schemas_dir)
            .unwrap_or(schema_path)
            .display()
    );
    fs::write(out_path, format!("{header}{rust}")).map_err(|err| {
        format!(
            "failed to write {}: {err}",
            out_path.display()
        )
    })?;
    Ok(())
}

fn main() {
    let root = repo_root();
    let schemas_dir = schemas_dir(&root);
    let source_schemas_dir = source_schemas_dir(&root);
    let out_root = root.join("crates/spoke-schemas/src/generated");

    fs::remove_dir_all(&out_root).ok();
    fs::create_dir_all(&out_root).expect("mkdir out");

    let pattern = schemas_dir.join("**/*.schema.json");
    let mut schema_paths: Vec<PathBuf> = glob(pattern.to_str().unwrap())
        .expect("glob pattern")
        .filter_map(Result::ok)
        .collect();
    schema_paths.sort();

    let mut generated_files: BTreeSet<PathBuf> = BTreeSet::new();
    let mut generated_modules: Vec<GeneratedModule> = Vec::new();
    let mut failures: Vec<String> = Vec::new();

    for schema_path in &schema_paths {
        let rel = schema_path.strip_prefix(&schemas_dir).expect("under schemas");
        let rel_parent = rel.parent().unwrap_or(Path::new("")).to_path_buf();
        let base = schema_path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("stem")
            .strip_suffix(".schema")
            .unwrap_or("schema");
        let rust_mod = to_rust_module_name(base);
        let out_path = out_root.join(&rel_parent).join(format!("{rust_mod}.rs"));

        let source_schema = source_schemas_dir.join(rel);
        let (export_all, export_type) = export_mode_for_schema(&source_schema);

        match generate_schema_rust(schema_path, &schemas_dir, &out_path) {
            Ok(()) => {
                generated_files.insert(out_path.clone());
                generated_modules.push(GeneratedModule {
                    rust_mod: rust_mod.clone(),
                    rel_parent,
                    export_all,
                    export_type,
                });
                println!(
                    "wrote {}",
                    out_path.strip_prefix(&root).unwrap().display()
                );
            }
            Err(err) => failures.push(err),
        }
    }

    if !failures.is_empty() {
        for err in &failures {
            eprintln!("error: {err}");
        }
        process::exit(1);
    }

    if generated_files.len() != EXPECTED_SCHEMA_COUNT {
        eprintln!(
            "error: expected {EXPECTED_SCHEMA_COUNT} Rust schema file(s), generated {}",
            generated_files.len()
        );
        process::exit(1);
    }

    for sub in ["", "common", "data", "ops"] {
        let dir = if sub.is_empty() {
            out_root.clone()
        } else {
            out_root.join(sub)
        };
        if !dir.exists() {
            continue;
        }

        let mut child_modules = Vec::new();

        if let Ok(entries) = fs::read_dir(&dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    child_modules.push(entry.file_name().to_string_lossy().into_owned());
                }
            }
        }

        child_modules.sort();

        let dir_modules: Vec<&GeneratedModule> = generated_modules
            .iter()
            .filter(|m| {
                let module_dir = if m.rel_parent.as_os_str().is_empty() {
                    out_root.clone()
                } else {
                    out_root.join(&m.rel_parent)
                };
                module_dir == dir
            })
            .collect();

        write_mod_rs(&dir, &child_modules, &dir_modules);
    }

    println!("Rust: {} file(s)", generated_files.len());
}
