//! Shared golden envelope-auth vector loader + consumer tests —
//! **test-only** (`#[cfg(test)]`).
//!
//! The golden envelope-auth vectors (Ed25519 seed, derived pubkey + peer id,
//! and per-family positive / negative wire envelopes with pinned RFC 8785
//! JCS bytes and signatures) live in
//! `tests/fixtures/golden-envelope-auth.json` — the single cross-language
//! source of truth, alongside `golden-hello.json`. This crate is the
//! historical capture authority, so the fixture sits under the crate and
//! tests load it with `include_str!` + `serde_json`.
//!
//! The vectors are **transcribed from committed constants** (generated by
//! the Rust core `authenticate_*` helpers at plan commit time), never
//! regenerated by running the code under test. Each family carries at
//! least one positive vector (a wire envelope whose pinned signature must
//! verify) and one negative vector (a tampered / stripped wire envelope
//! whose rejection kind is pinned). The sync gate
//! (`tooling/connect/golden-vector-sync.mjs`) keeps the TS fixture copy
//! byte-identical and the TS consumer
//! (`packages/spoke-connect-ts/tests/core/envelope-auth-golden.test.ts`)
//! verifies the same bytes with the same outcomes — the TS↔Rust parity
//! proof for `spoke-connect-session-jcs-v1` /
//! `spoke-connect-invoke-request-jcs-v1` / `spoke-connect-invoke-response-jcs-v1`.
//!
//! The consumer tests below close the loop in both directions:
//! 1. **Verify the pinned bytes** — every positive wire envelope verifies
//!    against the golden public key; every negative envelope is rejected
//!    with exactly the pinned kind.
//! 2. **Re-sign the pinned inputs** — rebuilding the sign input from the
//!    wire envelope and running `authenticate_*` reproduces the pinned JCS
//!    bytes and signature byte-for-byte (the Rust side of the parity proof;
//!    the TS consumer does the same over the registered fixture copy).
//!
//! This module is `#[cfg(test)]` and is never linked into non-test builds.

use crate::core::envelope_auth::EnvelopeAuthErrorKind;
use std::sync::LazyLock;

/// A pinned positive vector: a full wire envelope (JSON string, byte-exact)
/// whose `signature` must verify against the golden public key, plus the
/// pinned canonical bytes the signature covers.
#[derive(Debug, serde::Deserialize)]
pub(crate) struct PositiveVector {
    pub(crate) envelope_json: String,
    pub(crate) jcs_hex: String,
    pub(crate) signature_b64u: String,
}

/// A pinned negative vector: a wire envelope (JSON string) that must be
/// rejected with exactly `kind` (`envelope_auth_missing` /
/// `envelope_auth_invalid` / `envelope_auth_session_unbound`).
#[derive(Debug, serde::Deserialize)]
pub(crate) struct NegativeVector {
    pub(crate) envelope_json: String,
    pub(crate) kind: String,
}

/// One envelope family: ≥1 positive + ≥1 negative vector.
#[derive(Debug, serde::Deserialize)]
pub(crate) struct Family {
    pub(crate) positive: Vec<PositiveVector>,
    pub(crate) negative: Vec<NegativeVector>,
}

/// Raw parsed golden envelope-auth vector (field access is crate-test-facing).
#[derive(Debug, serde::Deserialize)]
pub(crate) struct GoldenEnvelopeAuth {
    pub(crate) seed_hex: String,
    pub(crate) pubkey_hex: String,
    pub(crate) peer_id: String,
    pub(crate) session: Family,
    pub(crate) invoke_request: Family,
    pub(crate) invoke_response: Family,
}

static GOLDEN: LazyLock<GoldenEnvelopeAuth> = LazyLock::new(|| {
    let fixture = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/golden-envelope-auth.json"
    ));
    serde_json::from_str(fixture).expect("tests/fixtures/golden-envelope-auth.json parses")
});

/// The parsed golden vector, parsed once per test process.
pub(crate) fn golden() -> &'static GoldenEnvelopeAuth {
    &GOLDEN
}

/// Map a pinned `kind` string to the locked error kind.
pub(crate) fn kind_of(s: &str) -> EnvelopeAuthErrorKind {
    match s {
        "envelope_auth_missing" => EnvelopeAuthErrorKind::Missing,
        "envelope_auth_invalid" => EnvelopeAuthErrorKind::Invalid,
        "envelope_auth_session_unbound" => EnvelopeAuthErrorKind::SessionUnbound,
        other => panic!("fixture pins an unknown kind: {other}"),
    }
}

/// Parse a pinned wire envelope to the `serde_json::Value` form the verify
/// helpers consume.
pub(crate) fn wire_of(envelope_json: &str) -> serde_json::Value {
    serde_json::from_str(envelope_json).expect("fixture envelope_json parses")
}

/// The golden signer's raw 32-byte Ed25519 seed (same key pair as
/// `golden-hello.json` — the golden host signs its own post-hello envelopes).
pub(crate) fn golden_seed() -> [u8; 32] {
    let hex = &golden().seed_hex;
    let mut out = [0u8; 32];
    for (i, byte) in out.iter_mut().enumerate() {
        *byte = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).expect("fixture seed_hex is hex");
    }
    out
}

/// The golden signer's raw 32-byte Ed25519 public key.
pub(crate) fn golden_pubkey() -> [u8; 32] {
    let hex = &golden().pubkey_hex;
    let mut out = [0u8; 32];
    for (i, byte) in out.iter_mut().enumerate() {
        *byte = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).expect("fixture pubkey_hex is hex");
    }
    out
}

/// Build a `SessionSignInput` from a wire envelope minus `signature` /
/// `extensions` (re-sign parity: the pinned signature must reproduce
/// byte-for-byte when the signer re-signs the received wire fields).
pub(crate) fn session_sign_input_from_wire(
    wire: &serde_json::Value,
) -> crate::core::SessionSignInput {
    crate::core::SessionSignInput {
        session_id: wire["session_id"].as_str().expect("session_id").to_string(),
        initiator_peer_id: wire["initiator_peer_id"]
            .as_str()
            .expect("initiator_peer_id")
            .to_string(),
        responder_peer_id: wire["responder_peer_id"]
            .as_str()
            .expect("responder_peer_id")
            .to_string(),
        opened_at: wire["opened_at"]
            .as_str()
            .expect("opened_at")
            .parse()
            .expect("RFC 3339 opened_at"),
        negotiated_capabilities: wire["negotiated_capabilities"]
            .as_array()
            .expect("negotiated_capabilities")
            .iter()
            .map(|v| v.as_str().expect("capability").to_string())
            .collect(),
        initial_sequence: wire["initial_sequence"].as_u64().expect("initial_sequence"),
    }
}

/// Build an `InvokeRequestSignInput` from a wire envelope minus
/// `signature` / `extensions` (`auth` conditional inclusion preserved).
pub(crate) fn invoke_request_sign_input_from_wire(
    wire: &serde_json::Value,
) -> crate::core::InvokeRequestSignInput {
    crate::core::InvokeRequestSignInput {
        session_id: wire["session_id"].as_str().expect("session_id").to_string(),
        sequence: wire["sequence"].as_i64().expect("sequence"),
        request_id: wire["request_id"].as_str().expect("request_id").to_string(),
        op: wire["op"].as_str().expect("op").to_string(),
        payload: wire["payload"].clone(),
        auth: wire.get("auth").cloned(),
    }
}

/// Reconstruct the response signed object (branch-exact) from the wire form.
pub(crate) fn invoke_response_sign_input_from_wire(
    wire: &serde_json::Value,
) -> crate::core::InvokeResponseSignInput {
    let session_id = wire["session_id"].as_str().expect("session_id").to_string();
    let sequence = wire["sequence"].as_i64().expect("sequence");
    let request_id = wire["request_id"].as_str().expect("request_id").to_string();
    if let Some(payload) = wire.get("payload") {
        crate::core::InvokeResponseSignInput::Success {
            session_id,
            sequence,
            request_id,
            payload: payload.clone(),
        }
    } else {
        crate::core::InvokeResponseSignInput::Error {
            session_id,
            sequence,
            request_id,
            error: serde_json::from_value(wire["error"].clone()).expect("error envelope"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::envelope_auth::{
        authenticate_invoke_request, authenticate_invoke_response, authenticate_session,
        verify_invoke_request_auth, verify_invoke_response_auth, verify_session_auth,
    };

    fn to_hex(bytes: &[u8]) -> String {
        bytes.iter().map(|b| format!("{b:02x}")).collect()
    }

    /// The signed object of a success/error response branch as JSON (the
    /// exact keys the signature covers, per the locked field tables) — used
    /// for the pinned-jcs parity check. The branch discriminator is
    /// implicit: exactly `payload` (success) or `error`, never both.
    fn response_signed_object_json(wire: &serde_json::Value) -> serde_json::Value {
        let mut object = serde_json::Map::new();
        object.insert("session_id".into(), wire["session_id"].clone());
        object.insert("sequence".into(), wire["sequence"].clone());
        object.insert("request_id".into(), wire["request_id"].clone());
        if let Some(payload) = wire.get("payload") {
            object.insert("payload".into(), payload.clone());
        } else {
            object.insert("error".into(), wire["error"].clone());
        }
        serde_json::Value::Object(object)
    }

    fn response_signature(response: &spoke_schemas::connect::ConnectInvokeResponse) -> String {
        match response {
            spoke_schemas::connect::ConnectInvokeResponse::Variant0 { signature, .. } => {
                signature.to_string()
            }
            spoke_schemas::connect::ConnectInvokeResponse::Variant1 { signature, .. } => {
                signature.to_string()
            }
        }
    }

    fn expect_kind(result: Result<(), crate::core::EnvelopeAuthError>, kind: &str) {
        let err = result.expect_err("expected an envelope-auth rejection");
        assert_eq!(
            err.kind(),
            Some(kind_of(kind)),
            "unexpected error for pinned kind {kind}: {err}"
        );
    }

    #[test]
    fn ssot_is_self_consistent() {
        let golden = golden();
        // The golden host (the fixture `peer_id`) is the session initiator;
        // the responder is the [0x0a; 32] role seed used across the
        // envelope-auth unit tests.
        let session_wire = wire_of(&golden.session.positive[0].envelope_json);
        assert_eq!(
            session_wire["initiator_peer_id"]
                .as_str()
                .expect("initiator"),
            golden.peer_id
        );
        assert_eq!(
            session_wire["responder_peer_id"]
                .as_str()
                .expect("responder"),
            "12D3KooWENTLiCwwoVwYNbKFEfmNdyHG1jxNn9oPB29JeeZXWjAb"
        );
        // Every pinned signature is the one carried by the envelope.
        for family in [
            &golden.session,
            &golden.invoke_request,
            &golden.invoke_response,
        ] {
            for positive in &family.positive {
                let wire = wire_of(&positive.envelope_json);
                assert_eq!(
                    wire["signature"].as_str().expect("signature"),
                    positive.signature_b64u,
                    "envelope signature must equal the pinned signature_b64u"
                );
            }
        }
        // Response positives cover both branches (never merged).
        assert_eq!(golden.invoke_response.positive.len(), 2);
        assert!(wire_of(&golden.invoke_response.positive[0].envelope_json)
            .get("payload")
            .is_some());
        assert!(wire_of(&golden.invoke_response.positive[1].envelope_json)
            .get("error")
            .is_some());
    }

    #[test]
    fn session_positive_verifies_and_resigns_byte_identical() {
        let golden = golden();
        let seed = golden_seed();
        let pubkey = golden_pubkey();
        let wire = wire_of(&golden.session.positive[0].envelope_json);
        let positive = &golden.session.positive[0];

        // 1. Verify the pinned wire envelope against the golden public key.
        verify_session_auth(
            &pubkey,
            &wire,
            wire["initiator_peer_id"].as_str().expect("initiator"),
            wire["responder_peer_id"].as_str().expect("responder"),
        )
        .expect("session positive vector verifies");

        // 2. Re-sign the wire fields: identical JCS bytes + signature.
        let input = session_sign_input_from_wire(&wire);
        assert_eq!(
            to_hex(&serde_jcs::to_vec(&input).expect("jcs")),
            positive.jcs_hex
        );
        let re_signed = authenticate_session(&seed, &input, Default::default()).expect("sign");
        assert_eq!(re_signed.signature.to_string(), positive.signature_b64u);
    }

    #[test]
    fn session_negative_rejects_with_pinned_kind() {
        let golden = golden();
        let pubkey = golden_pubkey();
        for negative in &golden.session.negative {
            let wire = wire_of(&negative.envelope_json);
            let result = verify_session_auth(
                &pubkey,
                &wire,
                wire["initiator_peer_id"].as_str().expect("initiator"),
                wire["responder_peer_id"].as_str().expect("responder"),
            );
            expect_kind(result, &negative.kind);
        }
    }

    #[test]
    fn invoke_request_positive_verifies_and_resigns_byte_identical() {
        let golden = golden();
        let seed = golden_seed();
        let pubkey = golden_pubkey();
        let wire = wire_of(&golden.invoke_request.positive[0].envelope_json);
        let positive = &golden.invoke_request.positive[0];

        verify_invoke_request_auth(
            &pubkey,
            &wire,
            wire["session_id"].as_str().expect("session_id"),
        )
        .expect("invoke-request positive vector verifies");

        let input = invoke_request_sign_input_from_wire(&wire);
        // The pinned vector carries `auth` — conditional inclusion must
        // reproduce it (a lost `auth` would change the signed bytes).
        assert!(input.auth.is_some(), "pinned request carries auth");
        assert_eq!(
            to_hex(&serde_jcs::to_vec(&input).expect("jcs")),
            positive.jcs_hex
        );
        let re_signed =
            authenticate_invoke_request(&seed, &input, Default::default()).expect("sign");
        assert_eq!(re_signed.signature.to_string(), positive.signature_b64u);
    }

    #[test]
    fn invoke_request_negative_rejects_with_pinned_kind() {
        let golden = golden();
        let pubkey = golden_pubkey();
        for negative in &golden.invoke_request.negative {
            let wire = wire_of(&negative.envelope_json);
            let result = verify_invoke_request_auth(
                &pubkey,
                &wire,
                wire["session_id"].as_str().expect("session_id"),
            );
            expect_kind(result, &negative.kind);
        }
    }

    #[test]
    fn invoke_response_positives_verify_both_branches_and_resign() {
        let golden = golden();
        let seed = golden_seed();
        let pubkey = golden_pubkey();
        for positive in &golden.invoke_response.positive {
            let wire = wire_of(&positive.envelope_json);

            verify_invoke_response_auth(
                &pubkey,
                &wire,
                wire["session_id"].as_str().expect("session_id"),
            )
            .expect("invoke-response positive vector verifies");

            let input = invoke_response_sign_input_from_wire(&wire);
            assert_eq!(
                to_hex(&serde_jcs::to_vec(&response_signed_object_json(&wire)).expect("jcs")),
                positive.jcs_hex
            );
            let re_signed =
                authenticate_invoke_response(&seed, &input, Default::default()).expect("sign");
            assert_eq!(response_signature(&re_signed), positive.signature_b64u);
        }
    }

    #[test]
    fn invoke_response_negative_rejects_with_pinned_kind() {
        let golden = golden();
        let pubkey = golden_pubkey();
        for negative in &golden.invoke_response.negative {
            let wire = wire_of(&negative.envelope_json);
            let result = verify_invoke_response_auth(
                &pubkey,
                &wire,
                wire["session_id"].as_str().expect("session_id"),
            );
            expect_kind(result, &negative.kind);
        }
    }
}
